/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/Icon.vue')['default']
    NavigationBottom: typeof import('./src/components/NavigationBottom.vue')['default']
    NavigationBrand: typeof import('./src/components/NavigationBrand.vue')['default']
    NavigationHeader: typeof import('./src/components/NavigationHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
